### ISSUE TITLE
JFixtureJUnitRunner does not call @Before methods

### ISSUE THREAD

**Issue by wellingtonsteve** [FlexTradeUKLtd/jfixture#24]
@RunWith(JFixtureJUnitRunner.class)
    public class SetupNotCalledTest {

      @Fixture String awesomeString;

      TestSubject testSubject;

      @Before
      public void setUp() throws Exception {
        testSubject = new TestSubject(awesomeString);
      }

      @Test
      public void awesomeTest() throws Exception {
        System.err.println(testSubject);
        // whatever
      }
    }

When `awesomeTest()` runs, `testSubject` is null. If I use the `@Rule` instead it works correctly

    public class SetupNotCalledTest {

      @Rule public FixtureRule fr = FixtureRule.initFixtures();
      @Fixture String awesomeString;

      TestSubject testSubject;

      @Before
      public void setUp() throws Exception {
        testSubject = new TestSubject(awesomeString);
      }

      @Test
      public void awesomeTest() throws Exception {
        System.err.println(testSubject);
        // whatever
      }
    }

--- 

I had a bit of a look at how `MockitoJUnitRunner` does this when initialising mocks:

    public JUnit45AndHigherRunnerImpl(Class<?> klass) throws InitializationError {
        runner = new BlockJUnit4ClassRunner(klass) {
            protected Statement withBefores(FrameworkMethod method, Object target,
                    Statement statement) {
                // init annotated mocks before tests
                MockitoAnnotations.initMocks(target);
                return super.withBefores(method, target, statement);
            }
        };
    }

It's calling `super.withBefores` which seems to nicely handle calling `@Before` for free. I'll have a go at changing `JFixtureJUnitRunner`/`JUnitJFixtureStatement` to do something similar.

**Comment by richkeenan** [comment]
Good spot @wellingtonsteve, thanks for the help!

**Comment by richkeenan** [comment]
Merged. Closing

**Comment by richkeenan** [comment]
Released in version 2.5.0
