### ISSUE TITLE
Static 'copy constructor' methods should not be used to create a specimen 

### ISSUE THREAD

**Issue by wellingtonsteve** [FlexTradeUKLtd/jfixture#30]
Some background first. We use another library, which given an interface such as the following:

    public interface InterfaceType {
        String getSymbol();  
        int getSize();
    }

generates an implementation which includes a static copy() method. Note the private constructor

    public class TypeWithCopyFactoryMethod implements InterfaceType {

        private final String symbol;
        private final int size;
  
        private TypeWithCopyFactoryMethod(String symbol, int size) {
            this.symbol = symbol;
            this.size = size;
        }
  
        public static TypeWithCopyFactoryMethod copy(InterfaceType source) {
            return new TypeWithCopyFactoryMethod(source.getSymbol(), source.getSize());
        }

        public static TypeWithCopyFactoryMethod create(String symbol, int size) {
            return new TypeWithCopyFactoryMethod(symbol, size);
        }

        @Override
        public String getSymbol() {
            return symbol;
        }

        @Override
        public int getSize() {
            return size;
        }
  
    }

If we try to use JFixture to generate an instance of TypeWithCopyFactoryMethod it fails, trying to use the copy() method instead of the create() method because the former has fewer parameters.

    java.lang.UnsupportedOperationException: JFixture was unable to create an instance of testtypes.factorymethods.InterfaceType
    Most likely because it has no public constructor, is an abstract or non-public type or has no static factory methods.
    If this isn't the case it's likely that all constructors and factory methods on the type have thrown an exception.
    To view any thrown exceptions just add the Tracing Customisation to the JFixture instance, e.g. fixture.customise(new TracingCustomisation(System.out));
        testtypes.factorymethods.TypeWithCopyFactoryMethod --> 
        testtypes.factorymethods.TypeWithCopyFactoryMethod copy(testtypes.factorymethods.InterfaceType) --> 
        testtypes.factorymethods.InterfaceType --> 
        testtypes.factorymethods.InterfaceType

This is only an issue with the interface; if you change the signature to `public static TypeWithCopyFactoryMethod copy(TypeWithCopyFactoryMethod source)` it works, presumably because the circular dependency is detected and `ClassToFactoryMethodRelay` automatically moves on to the next method.

Pull request to follow

**Comment by richkeenan** [comment]
This is great! Thanks @wellingtonsteve for the PR. I'll get that merged and push out a new version immediately

**Comment by richkeenan** [comment]
Thats's now been pushed to the Nexus OSS repo and will be available from Maven Central next time they sync (few hours usually). Thanks again for your contribution

**Comment by wellingtonsteve** [comment]
Rich, I'm only seeing version 2.6.2 for jfixture-parent, but not the underlying modules. Should it have synced by now?

**Comment by richkeenan** [comment]
Yea I just spotted that - weird. I'll look into right now

**Comment by richkeenan** [comment]
OK I've pushed a new release, 2.6.3 (it needs to be a new version number even though nothing changed). Looks like it was due to a recent change in my deployment script. Sorry for the inconvenience.

**Comment by wellingtonsteve** [comment]
No worries, thanks for the quick response.
